const STORAGE_KEY="fg_wc_auto_v1";let state=loadState(),currentList=[];
function loadState(){const s=localStorage.getItem(STORAGE_KEY);if(s){try{return JSON.parse(s)}catch(e){}}return JSON.parse(JSON.stringify(window.SEED_DATA))}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function activePlayers(team){return state.players.filter(p=>p.team===team&&p.status==="Titolare")}
function matchPlayers(m){return [...activePlayers(m.home),...activePlayers(m.away)]}
function topBonus(m){return matchPlayers(m).sort((a,b)=>b.bonus-a.bonus).slice(0,5)}
function cleanSheetGK(m){return matchPlayers(m).filter(p=>p.role==="POR").sort((a,b)=>b.bonus-a.bonus)[0]}
function firstYellow(m){return matchPlayers(m).sort((a,b)=>b.yellow-a.yellow)[0]}
function firstSub(m){return matchPlayers(m).filter(p=>p.role!=="POR").sort((a,b)=>b.sub-a.sub)[0]}
function stake(s){if(!s)return"-";if(s>=90)return"5u";if(s>=85)return"3u";if(s>=80)return"2u";if(s>=70)return"1u";return"No bet"}function scoreClass(s){if(s>=85)return"high";if(s>=70)return"mid";return"low"}function pills(a){return a.length?`<div class="pills">${a.map(p=>`<span class="pill">${p.name} · ${p.role}</span>`).join("")}</div>`:"-"}function matchTitle(m){return`${m.home} - ${m.away}`}
function card(m,mode="all"){const bonus=topBonus(m),gk=cleanSheetGK(m),yellow=firstYellow(m),sub=firstSub(m);let grid="";if(mode==="fantasy")grid=`<div class="grid"><div class="item"><span>PT</span><strong>${m.pt}</strong></div><div class="item"><span>FT</span><strong>${m.ft}</strong></div><div class="item full"><span>Top 5 Bonus</span>${pills(bonus)}</div><div class="item"><span>Clean Sheet GK</span><strong>${gk?gk.name:"-"}</strong></div><div class="item"><span>Primo ammonito</span><strong>${yellow?yellow.name:"-"}</strong></div><div class="item"><span>Primo sostituito</span><strong>${sub?sub.name:"-"}</strong></div></div>`;else if(mode==="betting")grid=`<div class="grid"><div class="item"><span>Safe</span><strong>${m.safe}</strong></div><div class="item"><span>Value</span><strong>${m.value}</strong></div><div class="item"><span>Quota Pazza</span><strong>${m.crazy}</strong></div><div class="item"><span>Combo</span><strong>${m.combo}</strong></div><div class="item"><span>BTTS</span><strong>${m.btts}</strong></div><div class="item"><span>Over/Under</span><strong>${m.over}</strong></div><div class="item"><span>Stake</span><strong>${stake(m.fg)}</strong></div><div class="item"><span>Affidabilità</span><strong>${m.confidence}/10</strong></div></div>`;else grid=`<div class="grid"><div class="item"><span>PT / FT</span><strong>${m.pt} → ${m.ft}</strong></div><div class="item"><span>FG Score</span><strong>${m.fg||"TBD"}</strong></div><div class="item"><span>Safe</span><strong>${m.safe}</strong></div><div class="item"><span>Value</span><strong>${m.value}</strong></div><div class="item full"><span>Top 5 Bonus</span>${pills(bonus)}</div></div>`;return`<article class="card"><div class="cardHead"><div><div class="matchTitle">${matchTitle(m)}</div><div class="meta">#${m.id} · ${m.date} · ${m.stage}${m.group?` · ${m.group}`:""} · ${m.venue}</div></div><div class="score ${scoreClass(m.fg)}">${m.fg||"TBD"}</div></div>${grid}<button class="ghost smallBtn" onclick="openDetail(${m.id})">Apri dettaglio</button></article>`}
function filtered(){const q=document.getElementById("search")?.value?.toLowerCase()||"",st=document.getElementById("stageFilter")?.value||"",gr=document.getElementById("groupFilter")?.value||"";return state.matches.filter(m=>(!q||matchTitle(m).toLowerCase().includes(q)||m.stage.toLowerCase().includes(q)||m.date.includes(q))&&(!st||m.stage===st)&&(!gr||m.group===gr))}
function renderAllCards(){currentList=filtered();document.getElementById("allCards").innerHTML=currentList.map(m=>card(m,"all")).join("");document.getElementById("kpiVisible").textContent=currentList.length;document.getElementById("kpiTotal").textContent=state.matches.length;const best=[...currentList].filter(m=>m.fg).sort((a,b)=>b.fg-a.fg)[0];document.getElementById("kpiFG").textContent=best?`${matchTitle(best)} ${best.fg}`:"-";let all=[];currentList.forEach(m=>topBonus(m).forEach(p=>all.push({...p,match:matchTitle(m)})));all.sort((a,b)=>b.bonus-a.bonus);document.getElementById("kpiBonus").textContent=all[0]?all[0].name:"-"}
function renderFantasy(){document.getElementById("fantasyCards").innerHTML=state.matches.map(m=>card(m,"fantasy")).join("")}function renderBetting(){document.getElementById("bettingCards").innerHTML=state.matches.map(m=>card(m,"betting")).join("")}function renderGroups(){document.getElementById("groupCards").innerHTML=Object.entries(state.groups).map(([g,t])=>`<div class="groupCard"><h3>Gruppo ${g}</h3><div class="teamList">${t.map(x=>`<span class="pill">${x}</span>`).join("")}</div></div>`).join("")}
function renderLineups(){const wrap=document.getElementById("lineupList");wrap.innerHTML=state.players.map((p,i)=>`<div class="playerRow"><div><strong>${p.name}</strong><div class="playerMeta">${p.team} · ${p.role} · bonus ${p.bonus} · giallo ${p.yellow} · sub ${p.sub}</div></div><select data-player="${i}"><option ${p.status==="Titolare"?"selected":""}>Titolare</option><option ${p.status==="Panchina"?"selected":""}>Panchina</option><option ${p.status==="Fuori"?"selected":""}>Fuori</option></select></div>`).join("");wrap.querySelectorAll("select").forEach(sel=>sel.addEventListener("change",e=>{state.players[+e.target.dataset.player].status=e.target.value;saveState();render()}))}
function renderBest(){const top=[...state.matches].filter(m=>m.fg).sort((a,b)=>b.fg-a.fg).slice(0,10);let all=[];state.matches.forEach(m=>topBonus(m).forEach(p=>all.push({...p,match:matchTitle(m)})));all.sort((a,b)=>b.bonus-a.bonus);document.getElementById("bestCards").innerHTML=`<article class="card"><h3>Top 10 FG Score</h3>${top.map(m=>`<div class="pill">${matchTitle(m)} · ${m.fg} · ${m.safe}</div>`).join(" ")}</article><article class="card"><h3>Top 20 Bonus</h3>${all.slice(0,20).map(p=>`<div class="pill">${p.name} · ${p.team} · ${p.bonus}</div>`).join(" ")}</article>`}
function fillFilters(){const s=document.getElementById("stageFilter"),g=document.getElementById("groupFilter");[...new Set(state.matches.map(m=>m.stage))].forEach(x=>s.insertAdjacentHTML("beforeend",`<option>${x}</option>`));[...new Set(state.matches.map(m=>m.group).filter(Boolean))].forEach(x=>g.insertAdjacentHTML("beforeend",`<option>${x}</option>`))}
function mergePlayers(players,sourceMatch){let added=0,updated=0;const teams=sourceMatch?[sourceMatch.home,sourceMatch.away]:Object.values(state.groups).flat();players.forEach(p=>{let name=(p.name||"").trim();if(!name||name.length<3)return;let existing=state.players.find(x=>x.name.toLowerCase()===name.toLowerCase());let team=p.team&&teams.includes(p.team)?p.team:(sourceMatch?guessTeamFromName(name,sourceMatch):p.team||"Sconosciuta");if(existing){existing.status=p.status||"Titolare";if(team!=="Sconosciuta")existing.team=team;updated++}else{state.players.push({team,name,role:p.role||"UNK",status:p.status||"Titolare",bonus:p.bonus||60,yellow:p.yellow||25,sub:p.sub||45});added++}});saveState();render();return{added,updated}}
function guessTeamFromName(name,m){return activePlayers(m.home).some(p=>p.name.toLowerCase()===name.toLowerCase())?m.home:activePlayers(m.away).some(p=>p.name.toLowerCase()===name.toLowerCase())?m.away:m.home}
function inferMatchFromUrlOrSelection(){const q=(document.getElementById("autoUrl").value||"").toLowerCase();return state.matches.find(m=>q.includes(m.home.toLowerCase())||q.includes(m.away.toLowerCase()))||state.matches[0]}
async function autoRead(){const url=document.getElementById("autoUrl").value.trim(),log=document.getElementById("autoLog");if(!url){log.textContent="Inserisci un URL.";return}log.textContent="Aggiornamento automatico in corso...";try{const res=await fetch("/api/scrape",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url})});const out=await res.json();if(!out.ok){log.textContent="Errore: "+out.error+"\nUsa fallback manuale.";return}const result=mergePlayers(out.players||[],inferMatchFromUrlOrSelection());log.textContent=`Aggiornamento completato.\nFonte: ${out.source}\nNomi trovati: ${(out.players||[]).length}\nAggiornati: ${result.updated}\nAggiunti: ${result.added}\nMetodo: ${out.method}\nNota: ${out.note||""}`}catch(e){log.textContent="Backend non raggiungibile. Devi pubblicare/avviare la versione server, non quella statica."}}
function parseLineupTextFrom(id){const raw=document.getElementById(id).value;let players=[];const teamNames=Object.values(state.groups).flat();raw.split(/\n|;/).map(x=>x.trim()).filter(Boolean).forEach(line=>{let team=teamNames.find(t=>line.toLowerCase().includes(t.toLowerCase()))||"";let clean=line.replace(/^[^:]{2,30}:/,"");clean.split(/,|\||•|·/).map(x=>x.trim()).filter(x=>x.length>2&&x.length<35&&!/formazione|panchina|allenatore|arbitro/i.test(x)).forEach(name=>players.push({team,name,status:"Titolare"}))});const result=mergePlayers(players,inferMatchFromUrlOrSelection());document.getElementById(id).value=`Aggiornati: ${result.updated}. Aggiunti: ${result.added}.`}
function openDetail(id){const m=state.matches.find(x=>x.id===id);const bonus=topBonus(m),gk=cleanSheetGK(m),yellow=firstYellow(m),sub=firstSub(m);document.getElementById("modalContent").innerHTML=`<h2>${matchTitle(m)}</h2><p>${m.date} · ${m.stage} · ${m.group||""} · ${m.venue}</p><div class="grid"><div class="item"><span>PT</span><strong>${m.pt}</strong></div><div class="item"><span>FT</span><strong>${m.ft}</strong></div><div class="item"><span>Safe</span><strong>${m.safe}</strong></div><div class="item"><span>Value</span><strong>${m.value}</strong></div><div class="item"><span>Quota Pazza</span><strong>${m.crazy}</strong></div><div class="item"><span>Combo</span><strong>${m.combo}</strong></div><div class="item full"><span>Top 5 Bonus</span>${pills(bonus)}</div><div class="item"><span>Clean Sheet</span><strong>${gk?gk.name:"-"}</strong></div><div class="item"><span>Primo ammonito</span><strong>${yellow?yellow.name:"-"}</strong></div><div class="item"><span>Primo sostituito</span><strong>${sub?sub.name:"-"}</strong></div></div>`;document.getElementById("modal").hidden=false}
function render(){renderAllCards();renderFantasy();renderBetting();renderGroups();renderLineups();renderBest()}
document.querySelectorAll(".tab").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(b=>b.classList.remove("active"));document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));btn.classList.add("active");document.getElementById(btn.dataset.tab).classList.add("active")}))
document.getElementById("search").addEventListener("input",renderAllCards);document.getElementById("stageFilter").addEventListener("change",renderAllCards);document.getElementById("groupFilter").addEventListener("change",renderAllCards);document.getElementById("parseLineup").addEventListener("click",()=>parseLineupTextFrom("lineupText"));document.getElementById("parseLineupAuto").addEventListener("click",()=>parseLineupTextFrom("lineupTextAuto"));document.getElementById("autoRead").addEventListener("click",autoRead);document.getElementById("resetData").addEventListener("click",()=>{localStorage.removeItem(STORAGE_KEY);state=JSON.parse(JSON.stringify(window.SEED_DATA));render()});document.getElementById("closeModal").addEventListener("click",()=>document.getElementById("modal").hidden=true);document.getElementById("modal").addEventListener("click",e=>{if(e.target.id==="modal")e.currentTarget.hidden=true})
if("serviceWorker"in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"))}
fillFilters();render();