
const STORAGE_KEY="fg_wc_montecarlo_v1";let state=loadState(),currentList=[];
function loadState(){const s=localStorage.getItem(STORAGE_KEY);if(s){try{return JSON.parse(s)}catch(e){}}return JSON.parse(JSON.stringify(window.SEED_DATA))}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function activePlayers(team){return state.players.filter(p=>p.team===team&&p.status==="Titolare")}
function matchPlayers(m){return [...activePlayers(m.home),...activePlayers(m.away)]}
function topBonus(m){return matchPlayers(m).sort((a,b)=>b.bonus-a.bonus).slice(0,5)}
function firstYellow(m){return matchPlayers(m).sort((a,b)=>b.yellow-a.yellow)[0]}
function firstSub(m){return matchPlayers(m).filter(p=>p.role!=="POR").sort((a,b)=>b.sub-a.sub)[0]}
function stake(s){if(!s)return"-";if(s>=90)return"5u";if(s>=85)return"3u";if(s>=80)return"2u";if(s>=70)return"1u";return"No bet"}function scoreClass(s){if(s>=85)return"high";if(s>=70)return"mid";return"low"}function pct(p){return`${Math.round(p*100)}%`}function fairOdds(p){return p>0?(1/p).toFixed(2):"-"}function pills(a){return a.length?`<div class="pills">${a.map(p=>`<span class="pill">${p.name} · ${p.role||""}</span>`).join("")}</div>`:"-"}function matchTitle(m){return`${m.home} - ${m.away}`}
function mulberry32(a){return function(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}function hashString(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}function poisson(lambda,rand){const L=Math.exp(lambda*-1);let k=0,p=1;do{k++;p*=rand()}while(p>L);return k-1}function clamp(x,a,b){return Math.max(a,Math.min(b,x))}
function teamRating(team){const ps=state.players.filter(p=>p.team===team);if(!ps.length)return 70;const active=ps.filter(p=>p.status==="Titolare");const pool=active.length?active:ps;const avg=pool.reduce((s,p)=>s+(p.bonus||60),0)/pool.length;const gk=pool.find(p=>p.role==="POR");const att=pool.filter(p=>p.role==="ATT");const attack=att.reduce((s,p)=>s+(p.bonus||60),0)/Math.max(1,att.length);return clamp(avg*.65+attack*.25+(gk?gk.bonus*.10:6),50,98)}
function expectedGoals(h,a){const rh=teamRating(h),ra=teamRating(a),diff=rh-ra;return[clamp(1.35+diff*.035,.25,3.6),clamp(1.05-diff*.030,.20,3.2)]}
function runMonteCarlo(m,n=10000){if(!m||m.home.includes("Team ")||m.away.includes("Team "))return null;const[lh,la]=expectedGoals(m.home,m.away),rand=mulberry32(hashString(m.home+"|"+m.away+"|"+m.date));const exact={},htExact={};let hw=0,d=0,aw=0,o=0,u=0,b=0,hcs=0,acs=0,hhlead=0,htd=0,ahlead=0;for(let i=0;i<n;i++){const hg=poisson(lh,rand),ag=poisson(la,rand);if(hg>ag)hw++;else if(hg===ag)d++;else aw++;if(hg+ag>2.5)o++;else u++;if(hg>0&&ag>0)b++;if(ag===0)hcs++;if(hg===0)acs++;exact[`${hg}-${ag}`]=(exact[`${hg}-${ag}`]||0)+1;const hh=poisson(lh*.45,rand),ah=poisson(la*.45,rand);htExact[`${hh}-${ah}`]=(htExact[`${hh}-${ah}`]||0)+1;if(hh>ah)hhlead++;else if(hh===ah)htd++;else ahlead++}const exactTop=Object.entries(exact).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([score,c])=>({score,prob:c/n}));const htTop=Object.entries(htExact).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([score,c])=>({score,prob:c/n}));const probs={homeWin:hw/n,draw:d/n,awayWin:aw/n,over25:o/n,under25:u/n,btts:b/n,homeCS:hcs/n,awayCS:acs/n,htHomeLead:hhlead/n,htDraw:htd/n,htAwayLead:ahlead/n};const best=Object.entries({[`${m.home} vince`]:probs.homeWin,"Pareggio":probs.draw,[`${m.away} vince`]:probs.awayWin,"Over 2.5":probs.over25,"Under 2.5":probs.under25,"BTTS Sì":probs.btts,[`Clean sheet ${m.home}`]:probs.homeCS,[`Clean sheet ${m.away}`]:probs.awayCS}).sort((a,b)=>b[1]-a[1])[0];return{lambdaHome:lh,lambdaAway:la,probs,exactTop,htTop,bestMarket:{name:best[0],prob:best[1],fair:fairOdds(best[1])},fg:Math.round(clamp(55+best[1]*45,55,98))}}
function applyMonteCarloToMatches(){state.matches.forEach(m=>{const sim=runMonteCarlo(m,10000);if(!sim){m.sim=null;return}m.sim=sim;m.fg=sim.fg;m.pt=sim.htTop[0]?.score||m.pt;m.ft=sim.exactTop[0]?.score||m.ft;m.btts=sim.probs.btts>=.5?"Sì":"No";m.over=sim.probs.over25>=sim.probs.under25?"Over 2.5":"Under 2.5";m.safe=sim.bestMarket.name+` (fair ${sim.bestMarket.fair})`;const value=Object.entries({"Over 2.5":sim.probs.over25,"Under 2.5":sim.probs.under25,"BTTS Sì":sim.probs.btts,[`${m.home} DNB`]:sim.probs.homeWin/(sim.probs.homeWin+sim.probs.awayWin),[`${m.away} DNB`]:sim.probs.awayWin/(sim.probs.homeWin+sim.probs.awayWin)}).sort((a,b)=>b[1]-a[1])[0];m.value=`${value[0]} · quota min ${fairOdds(value[1])}`;const crazy=sim.exactTop.find(x=>x.prob<.16)||sim.exactTop[1]||sim.exactTop[0];m.crazy=`Risultato esatto ${crazy.score} · fair ${fairOdds(crazy.prob)}`;m.combo=`${sim.htTop[0]?.score||"0-0"} / ${sim.exactTop[0]?.score||"1-1"}`;m.confidence=Number((m.fg/10).toFixed(1))});saveState()}
function fantasyBonusScore(p,m){const sim=m.sim||runMonteCarlo(m,3000);let base=(p.bonus||60)/100,cs=0;if(sim){if(p.team===m.home)cs=sim.probs.homeCS;if(p.team===m.away)cs=sim.probs.awayCS}let mult=p.role==="POR"?.55+cs*.75:p.role==="ATT"?1.15:p.role==="CEN"?.95:.80;return Math.round(100*clamp(base*mult,.05,.99))}
function topBonusMC(m){return matchPlayers(m).map(p=>({...p,fantasyScore:fantasyBonusScore(p,m)})).sort((a,b)=>b.fantasyScore-a.fantasyScore).slice(0,5)}function cleanSheetGKMC(m){return matchPlayers(m).filter(p=>p.role==="POR").map(p=>({...p,fantasyScore:fantasyBonusScore(p,m)})).sort((a,b)=>b.fantasyScore-a.fantasyScore)[0]}
function card(m,mode="all"){const bonus=topBonusMC(m),gk=cleanSheetGKMC(m),yellow=firstYellow(m),sub=firstSub(m),sim=m.sim;let grid="";if(mode==="fantasy")grid=`<div class="grid"><div class="item"><span>PT simulato</span><strong>${m.pt}</strong></div><div class="item"><span>FT simulato</span><strong>${m.ft}</strong></div><div class="item full"><span>Top 5 Bonus MC</span>${pills(bonus.map(p=>({...p,name:`${p.name} ${p.fantasyScore}`})))}</div><div class="item"><span>Clean Sheet GK</span><strong>${gk?`${gk.name} ${gk.fantasyScore}`:"-"}</strong></div><div class="item"><span>Primo ammonito</span><strong>${yellow?yellow.name:"-"}</strong></div><div class="item"><span>Primo sostituito</span><strong>${sub?sub.name:"-"}</strong></div></div>`;else if(mode==="betting")grid=`<div class="grid"><div class="item"><span>Safe</span><strong>${m.safe}</strong></div><div class="item"><span>Value</span><strong>${m.value}</strong></div><div class="item"><span>Quota Pazza</span><strong>${m.crazy}</strong></div><div class="item"><span>Combo</span><strong>${m.combo}</strong></div><div class="item"><span>BTTS</span><strong>${m.btts} ${sim?pct(sim.probs.btts):""}</strong></div><div class="item"><span>Over/Under</span><strong>${m.over}</strong></div><div class="item"><span>Stake</span><strong>${stake(m.fg)}</strong></div><div class="item"><span>Affidabilità</span><strong>${m.confidence}/10</strong></div></div>`;else grid=`<div class="grid"><div class="item"><span>PT / FT</span><strong>${m.pt} → ${m.ft}</strong></div><div class="item"><span>FG Score</span><strong>${m.fg||"TBD"}</strong></div><div class="item"><span>Safe</span><strong>${m.safe}</strong></div><div class="item"><span>Value</span><strong>${m.value}</strong></div><div class="item full"><span>Top 5 Bonus</span>${pills(bonus.map(p=>({...p,name:`${p.name} ${p.fantasyScore}`})))}</div>${sim?`<div class="item"><span>1X2</span><strong>1 ${pct(sim.probs.homeWin)} · X ${pct(sim.probs.draw)} · 2 ${pct(sim.probs.awayWin)}</strong></div><div class="item"><span>Gol</span><strong>O2.5 ${pct(sim.probs.over25)} · BTTS ${pct(sim.probs.btts)}</strong></div>`:""}</div>`;return`<article class="card"><div class="cardHead"><div><div class="matchTitle">${matchTitle(m)}</div><div class="meta">#${m.id} · ${m.date} · ${m.stage}${m.group?` · ${m.group}`:""} · ${m.venue}</div></div><div class="score ${scoreClass(m.fg)}">${m.fg||"TBD"}</div></div>${grid}<button class="ghost smallBtn" onclick="openDetail(${m.id})">Apri dettaglio</button></article>`}
function filtered(){const q=document.getElementById("search")?.value?.toLowerCase()||"",st=document.getElementById("stageFilter")?.value||"",gr=document.getElementById("groupFilter")?.value||"";return state.matches.filter(m=>(!q||matchTitle(m).toLowerCase().includes(q)||m.stage.toLowerCase().includes(q)||m.date.includes(q))&&(!st||m.stage===st)&&(!gr||m.group===gr))}
function renderAllCards(){currentList=filtered();document.getElementById("allCards").innerHTML=currentList.map(m=>card(m,"all")).join("");document.getElementById("kpiVisible").textContent=currentList.length;document.getElementById("kpiTotal").textContent=state.matches.length;const best=[...currentList].filter(m=>m.fg).sort((a,b)=>b.fg-a.fg)[0];document.getElementById("kpiFG").textContent=best?`${matchTitle(best)} ${best.fg}`:"-";let all=[];currentList.forEach(m=>topBonusMC(m).forEach(p=>all.push({...p,match:matchTitle(m)})));all.sort((a,b)=>b.fantasyScore-a.fantasyScore);document.getElementById("kpiBonus").textContent=all[0]?`${all[0].name} ${all[0].fantasyScore}`:"-"}
function renderFantasy(){document.getElementById("fantasyCards").innerHTML=state.matches.map(m=>card(m,"fantasy")).join("")}function renderBetting(){document.getElementById("bettingCards").innerHTML=state.matches.map(m=>card(m,"betting")).join("")}function renderMC(){document.getElementById("mcCards").innerHTML=state.matches.filter(m=>m.sim).map(m=>{const s=m.sim;return`<article class="card"><div class="cardHead"><div><div class="matchTitle">${matchTitle(m)}</div><div class="meta">${m.date} · ${m.group}</div></div><div class="score ${scoreClass(m.fg)}">${m.fg}</div></div><div class="grid"><div class="item"><span>1X2</span><strong>1 ${pct(s.probs.homeWin)} · X ${pct(s.probs.draw)} · 2 ${pct(s.probs.awayWin)}</strong></div><div class="item"><span>Fair 1X2</span><strong>1 ${fairOdds(s.probs.homeWin)} · X ${fairOdds(s.probs.draw)} · 2 ${fairOdds(s.probs.awayWin)}</strong></div><div class="item"><span>Gol</span><strong>O2.5 ${pct(s.probs.over25)} · U2.5 ${pct(s.probs.under25)}</strong></div><div class="item"><span>BTTS</span><strong>${pct(s.probs.btts)}</strong></div><div class="item"><span>Clean Sheet</span><strong>${m.home} ${pct(s.probs.homeCS)} · ${m.away} ${pct(s.probs.awayCS)}</strong></div><div class="item"><span>Expected Goals</span><strong>${s.lambdaHome.toFixed(2)} - ${s.lambdaAway.toFixed(2)}</strong></div><div class="item full"><span>Exact Top</span><strong>${s.exactTop.map(x=>`${x.score} ${pct(x.prob)} fair ${fairOdds(x.prob)}`).join(" · ")}</strong></div></div></article>`}).join("")}
function renderGroups(){document.getElementById("groupCards").innerHTML=Object.entries(state.groups).map(([g,t])=>`<div class="groupCard"><h3>Gruppo ${g}</h3><div class="teamList">${t.map(x=>`<span class="pill">${x}</span>`).join("")}</div></div>`).join("")}
function renderLineups(){const wrap=document.getElementById("lineupList");wrap.innerHTML=state.players.map((p,i)=>`<div class="playerRow"><div><strong>${p.name}</strong><div class="playerMeta">${p.team} · ${p.role} · bonus ${p.bonus} · giallo ${p.yellow} · sub ${p.sub}</div></div><select data-player="${i}"><option ${p.status==="Titolare"?"selected":""}>Titolare</option><option ${p.status==="Panchina"?"selected":""}>Panchina</option><option ${p.status==="Fuori"?"selected":""}>Fuori</option></select></div>`).join("");wrap.querySelectorAll("select").forEach(sel=>sel.addEventListener("change",e=>{state.players[+e.target.dataset.player].status=e.target.value;applyMonteCarloToMatches();render()}))}
function renderBest(){const top=[...state.matches].filter(m=>m.fg).sort((a,b)=>b.fg-a.fg).slice(0,10);let all=[];state.matches.forEach(m=>topBonusMC(m).forEach(p=>all.push({...p,match:matchTitle(m)})));all.sort((a,b)=>b.fantasyScore-a.fantasyScore);document.getElementById("bestCards").innerHTML=`<article class="card"><h3>Top 10 FG Score</h3>${top.map(m=>`<div class="pill">${matchTitle(m)} · ${m.fg} · ${m.safe}</div>`).join(" ")}</article><article class="card"><h3>Top 20 Bonus MC</h3>${all.slice(0,20).map(p=>`<div class="pill">${p.name} · ${p.team} · ${p.fantasyScore}</div>`).join(" ")}</article>`}
function fillFilters(){const s=document.getElementById("stageFilter"),g=document.getElementById("groupFilter");if(s.options.length>1)return;[...new Set(state.matches.map(m=>m.stage))].forEach(x=>s.insertAdjacentHTML("beforeend",`<option>${x}</option>`));[...new Set(state.matches.map(m=>m.group).filter(Boolean))].forEach(x=>g.insertAdjacentHTML("beforeend",`<option>${x}</option>`))}
function mergePlayers(players,sourceMatch){let added=0,updated=0;players.forEach(p=>{let name=(p.name||"").trim();if(!name||name.length<3)return;let existing=state.players.find(x=>x.name.toLowerCase()===name.toLowerCase());let team=p.team||sourceMatch?.home||"Sconosciuta";if(existing){existing.status=p.status||"Titolare";if(team!=="Sconosciuta")existing.team=team;updated++}else{state.players.push({team,name,role:p.role||"UNK",status:p.status||"Titolare",bonus:p.bonus||60,yellow:p.yellow||25,sub:p.sub||45});added++}});applyMonteCarloToMatches();return{added,updated}}
function inferMatchFromUrlOrSelection(){const q=(document.getElementById("autoUrl")?.value||"").toLowerCase();return state.matches.find(m=>q.includes(m.home.toLowerCase())||q.includes(m.away.toLowerCase()))||state.matches[0]}
async function autoRead(){const url=document.getElementById("autoUrl").value.trim(),log=document.getElementById("autoLog");if(!url){log.textContent="Inserisci un URL.";return}log.textContent="Aggiornamento automatico in corso...";try{const res=await fetch("/api/scrape",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url})});const out=await res.json();if(!out.ok){log.textContent="Errore: "+out.error+"\nUsa fallback manuale.";return}const result=mergePlayers(out.players||[],inferMatchFromUrlOrSelection());log.textContent=`Aggiornamento completato.\nFonte: ${out.source}\nNomi trovati: ${(out.players||[]).length}\nAggiornati: ${result.updated}\nAggiunti: ${result.added}\nMetodo: ${out.method}\nMonte Carlo ricalcolato.`;render()}catch(e){log.textContent="Backend non raggiungibile. Pubblica/avvia la versione server."}}
function parseLineupTextFrom(id){const raw=document.getElementById(id).value;let players=[];const teamNames=Object.values(state.groups).flat();raw.split(/\n|;/).map(x=>x.trim()).filter(Boolean).forEach(line=>{let team=teamNames.find(t=>line.toLowerCase().includes(t.toLowerCase()))||"";let clean=line.replace(/^[^:]{2,30}:/,"");clean.split(/,|\||•|·/).map(x=>x.trim()).filter(x=>x.length>2&&x.length<35&&!/formazione|panchina|allenatore|arbitro/i.test(x)).forEach(name=>players.push({team,name,status:"Titolare"}))});const result=mergePlayers(players,inferMatchFromUrlOrSelection());document.getElementById(id).value=`Aggiornati: ${result.updated}. Aggiunti: ${result.added}. Monte Carlo ricalcolato.`;render()}
function openDetail(id){const m=state.matches.find(x=>x.id===id);const bonus=topBonusMC(m),gk=cleanSheetGKMC(m),yellow=firstYellow(m),sub=firstSub(m),sim=m.sim;document.getElementById("modalContent").innerHTML=`<h2>${matchTitle(m)}</h2><p>${m.date} · ${m.stage} · ${m.group||""} · ${m.venue}</p><div class="grid"><div class="item"><span>PT</span><strong>${m.pt}</strong></div><div class="item"><span>FT</span><strong>${m.ft}</strong></div><div class="item"><span>Safe</span><strong>${m.safe}</strong></div><div class="item"><span>Value</span><strong>${m.value}</strong></div><div class="item"><span>Quota Pazza</span><strong>${m.crazy}</strong></div><div class="item"><span>Combo</span><strong>${m.combo}</strong></div>${sim?`<div class="item"><span>1X2</span><strong>1 ${pct(sim.probs.homeWin)} · X ${pct(sim.probs.draw)} · 2 ${pct(sim.probs.awayWin)}</strong></div><div class="item"><span>Fair odds</span><strong>1 ${fairOdds(sim.probs.homeWin)} · X ${fairOdds(sim.probs.draw)} · 2 ${fairOdds(sim.probs.awayWin)}</strong></div><div class="item"><span>Over/BTTS</span><strong>O2.5 ${pct(sim.probs.over25)} · BTTS ${pct(sim.probs.btts)}</strong></div><div class="item"><span>Clean Sheet</span><strong>${m.home} ${pct(sim.probs.homeCS)} · ${m.away} ${pct(sim.probs.awayCS)}</strong></div><div class="item full"><span>Risultati esatti</span><strong>${sim.exactTop.map(x=>`${x.score} ${pct(x.prob)} fair ${fairOdds(x.prob)}`).join(" · ")}</strong></div>`:""}<div class="item full"><span>Top 5 Bonus</span>${pills(bonus.map(p=>({...p,name:`${p.name} ${p.fantasyScore}`})))}</div><div class="item"><span>Clean Sheet GK</span><strong>${gk?`${gk.name} ${gk.fantasyScore}`:"-"}</strong></div><div class="item"><span>Primo ammonito</span><strong>${yellow?yellow.name:"-"}</strong></div><div class="item"><span>Primo sostituito</span><strong>${sub?sub.name:"-"}</strong></div></div>`;document.getElementById("modal").hidden=false}
function render(){renderAllCards();renderFantasy();renderBetting();renderMC();renderGroups();renderLineups();renderBest()}
document.querySelectorAll(".tab").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(b=>b.classList.remove("active"));document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));btn.classList.add("active");document.getElementById(btn.dataset.tab).classList.add("active")}))
document.getElementById("search").addEventListener("input",renderAllCards);document.getElementById("stageFilter").addEventListener("change",renderAllCards);document.getElementById("groupFilter").addEventListener("change",renderAllCards);
document.getElementById("parseLineup").addEventListener("click",()=>parseLineupTextFrom("lineupText"));document.getElementById("parseLineupAuto").addEventListener("click",()=>parseLineupTextFrom("lineupTextAuto"));document.getElementById("autoRead").addEventListener("click",autoRead);
document.getElementById("resetData").addEventListener("click",()=>{localStorage.removeItem(STORAGE_KEY);state=JSON.parse(JSON.stringify(window.SEED_DATA));applyMonteCarloToMatches();render()});
document.getElementById("closeModal").addEventListener("click",()=>document.getElementById("modal").hidden=true);document.getElementById("modal").addEventListener("click",e=>{if(e.target.id==="modal")e.currentTarget.hidden=true});
if("serviceWorker"in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"))}
fillFilters();applyMonteCarloToMatches();render();
