import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import * as cheerio from "cheerio";
import { chromium } from "playwright";
const __filename=fileURLToPath(import.meta.url);const __dirname=path.dirname(__filename);const app=express();app.use(express.json({limit:"3mb"}));app.use(express.static(__dirname));const PORT=process.env.PORT||3000;
function clean(s){return(s||"").replace(/\s+/g," ").trim()}
function allowedUrl(raw){const u=new URL(raw);const h=u.hostname.replace(/^www\./,"").replace(/^m\./,"");return h.endsWith("sofascore.com")||h.endsWith("diretta.it")||h.endsWith("flashscore.com")}
function teamOfLine(line,home,away){const l=line.toLowerCase();if(home&&l.includes(home.toLowerCase()))return home;if(away&&l.includes(away.toLowerCase()))return away;return ""}
function extractNames(text,home="",away=""){const blacklist=new Set(["SofaScore","Diretta","Flashscore","Football","Calcio","Partita","Statistiche","Classifiche","Quote","Formazioni","Panchina","Titolari","Allenatore","Arbitro","Stadio","Mondiali","World Cup","Live","Risultati","News","Home","Away","Info","H2H","Odds","Table","Standings"]);const players=[];const lines=text.split(/\n|•|·|\|/).map(clean).filter(Boolean);let currentTeam="";for(const line of lines){const t=teamOfLine(line,home,away);if(t)currentTeam=t;const re=/\b[A-ZÀ-ÖØ-Ý][a-zà-öø-ÿ'’.-]{2,}(?:\s+[A-ZÀ-ÖØ-Ý][a-zà-öø-ÿ'’.-]{2,}){0,2}\b/g;let m;while((m=re.exec(line))){const name=clean(m[0]);if(name.length<4||name.length>36)continue;if(blacklist.has(name))continue;if(/\d/.test(name))continue;if(home&&name.toLowerCase()===home.toLowerCase())continue;if(away&&name.toLowerCase()===away.toLowerCase())continue;if(players.some(p=>p.name===name))continue;players.push({name,team:currentTeam,status:"Titolare",role:"UNK",bonus:60,yellow:25,sub:45})}}return players.slice(0,80)}
function extractFromHtml(html,home,away){const $=cheerio.load(html);$("script,style,noscript,svg").remove();const parts=[];$("[title]").each((_,el)=>parts.push($(el).attr("title")));$("[aria-label]").each((_,el)=>parts.push($(el).attr("aria-label")));$("[data-testid]").each((_,el)=>parts.push($(el).text()));parts.push($("body").text());return extractNames(parts.join("\n"),home,away)}
async function scrapeWithPlaywright(url,home,away){const browser=await chromium.launch({headless:true,args:["--no-sandbox","--disable-setuid-sandbox"]});try{const page=await browser.newPage({userAgent:"Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Version/17.0 Mobile Safari/604.1",locale:"it-IT"});await page.goto(url,{waitUntil:"domcontentloaded",timeout:30000});await page.waitForTimeout(5000);const html=await page.content();return extractFromHtml(html,home,away)}finally{await browser.close()}}
app.get("/",(_,res)=>res.sendFile(path.join(__dirname,"index.html")));
app.post("/api/scrape",async(req,res)=>{const{url,home,away}=req.body||{};if(!url)return res.json({ok:false,error:"URL mancante"});try{if(!allowedUrl(url))return res.json({ok:false,error:"Sono consentiti solo SofaScore, Diretta o Flashscore."});let players=[],method="fetch+cheerio";try{const r=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Version/17.0 Mobile Safari/604.1","Accept-Language":"it-IT,it;q=0.9,en;q=0.8"}});if(r.ok)players=extractFromHtml(await r.text(),home,away)}catch(e){}if(players.length<8){method="playwright";players=await scrapeWithPlaywright(url,home,away)}res.json({ok:true,source:url,method,players,note:"Estrazione sperimentale. La V2 aggiorna il match selezionato e mostra casa/trasferta importate."})}catch(e){res.json({ok:false,error:e.message})}});
app.get("/health",(_,res)=>res.json({ok:true,version:"v2"}));app.listen(PORT,()=>console.log(`FG World Cup AI V2 attiva su http://localhost:${PORT}`));
