import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import * as cheerio from "cheerio";
import { chromium } from "playwright";
const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename),app=express();app.use(express.json({limit:"3mb"}));app.use(express.static(__dirname));const PORT=process.env.PORT||3000;
function clean(s){return(s||"").replace(/\s+/g," ").trim()}
function validName(n,h,a){const bad=["SofaScore","Diretta","Flashscore","Football","Calcio","Partita","Statistiche","Classifiche","Quote","Formazioni","Panchina","Titolari","Allenatore","Arbitro","Stadio","Mondiali","World Cup","Live","Risultati","News","Lineups","Formation"];return n&&n.length>=4&&n.length<36&&!/\d/.test(n)&&!bad.includes(n)&&n.toLowerCase()!==h.toLowerCase()&&n.toLowerCase()!==a.toLowerCase()}
function extract(text,h,a){const low=text.toLowerCase();if(!["lineups","formazioni","starting xi","titolari","formation"].some(x=>low.includes(x)))return[];let start=Math.min(...["lineups","formazioni","starting xi","titolari","formation"].map(x=>low.indexOf(x)).filter(i=>i>=0));let seg=text.slice(start,start+12000),re=/\b[A-ZÀ-ÖØ-Ý][a-zà-öø-ÿ'’.-]{2,}(?:\s+[A-ZÀ-ÖØ-Ý][a-zà-öø-ÿ'’.-]{2,}){0,2}\b/g,out=[],m;while((m=re.exec(seg))){let name=clean(m[0]);if(validName(name,h,a)&&!out.some(p=>p.name===name))out.push({name,status:"Titolare",role:"UNK",bonus:60,yellow:25,sub:45})}if(out.length<16)return[];out.slice(0,11).forEach(p=>p.team=h);out.slice(11,22).forEach(p=>p.team=a);return out.slice(0,22)}
function fromHtml(html,h,a){const $=cheerio.load(html);$("script,style,noscript,svg").remove();let txt=$("body").text()+" "+$("[title]").map((_,e)=>$(e).attr("title")).get().join(" ")+" "+$("[aria-label]").map((_,e)=>$(e).attr("aria-label")).get().join(" ");return extract(clean(txt),h,a)}
async function pw(url,h,a){const browser=await chromium.launch({headless:true,args:["--no-sandbox","--disable-setuid-sandbox"]});try{const page=await browser.newPage({userAgent:"Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Version/17.0 Mobile Safari/604.1",locale:"it-IT"});await page.goto(url,{waitUntil:"domcontentloaded",timeout:30000});await page.waitForTimeout(5000);return fromHtml(await page.content(),h,a)}finally{await browser.close()}}
app.get("/",(_,res)=>res.sendFile(path.join(__dirname,"index.html")));
app.post("/api/find-lineups",async(req,res)=>{const{home,away}=req.body||{};if(!home||!away)return res.json({ok:false,error:"Squadre mancanti"});const urls=[`https://www.sofascore.com/search/all?q=${encodeURIComponent(home+" "+away)}`,`https://www.diretta.it/cerca/?q=${encodeURIComponent(home+" "+away)}`];for(const url of urls){try{let r=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0","Accept-Language":"it-IT,it;q=0.9"}});if(r.ok){let p=fromHtml(await r.text(),home,away);if(p.length>=16)return res.json({ok:true,source:url,method:"fetch",players:p})}}catch(e){}try{let p=await pw(url,home,away);if(p.length>=16)return res.json({ok:true,source:url,method:"playwright",players:p})}catch(e){}}res.json({ok:false,error:"Formazioni non disponibili: nessun import casuale.",players:[]})});
app.listen(PORT,()=>console.log("FG World Cup AI V3 on "+PORT));
